name: CinemaStarApp
options:
  bundleIdPrefix: com.bundleId
  postGenCommand: pod update
  deploymentTarget: "16.0"
packages:
  KeychainSwift:
    url: https://github.com/evgenyneu/keychain-swift.git
    majorVersion: 24.0.0
targets:
  CinemaStarApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - CinemaStarApp
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1.0.0
        IPHONEOS_DEPLOYMENT_TARGET: 15.2
        MARKETING_VERSION: 1
        ENABLE_USER_SCRIPT_SANDBOXING: false


        INFOPLIST_KEY_UILaunchScreen_Generation: true

        ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - package: KeychainSwift
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
